In [1]:
# import libraries
import pandas as pd
import numpy as np
import os
from sklearn.ensemble import RandomForestClassifier
import datetime
from dateutil.parser import parse

In [2]:
# csv file path
all_incidents_csv = "incident_data/yearly_incident_data/all_incidents.csv"

# Import the csv file into data frame
all_incidents_df = pd.read_csv(all_incidents_csv, encoding="utf-8", low_memory = False)



all_incidents_df.head()
# print(all_incidents_df.dtypes)

,publicAddress,caseNumber,precinct,offense,description,ucrCode,lat,lon,neighborhood,incidentDate,incidentTime
0,0056Xx Lyndale Av S,MP2010000051,5,CSCR,Crim Sex Cond-Rape,3.0,44.900291,-93.288239,Windom,2010/01/01,00:30
1,0001Xx 62 St W,MP2010000099,5,ROBPAG,Robbery Per Agg,4.0,44.890636,-93.280041,Windom,2010/01/01,01:05
2,0039Xx 5 Av S,MP2010000373,3,BURGD,Burglary Of Dwelling,6.0,44.931448,-93.268841,Bryant,2010/01/01,04:18
3,0013Xx Nicollet Av S,MP2010000305,1,ASLT2,Asslt W/Dngrs Weapon,5.0,44.970506,-93.277714,Loring Park,2010/01/01,03:00
4,0034Xx Oliver Av N,MP2010000229,4,BURGD,Burglary Of Dwelling,6.0,45.017746,-93.306988,Folwell,2010/01/01,02:23

In [4]:
target = all_incidents_df['ucrCode']
target_binary_encoded = pd.get_dummies(target)
target_binary_encoded.head()
# target

   1.0   3.0   4.0   5.0   6.0   7.0   8.0   10.0
0     0     1     0     0     0     0     0     0
1     0     0     1     0     0     0     0     0
2     0     0     0     0     1     0     0     0
3     0     0     0     1     0     0     0     0
4     0     0     0     0     1     0     0     0

In [22]:
#Drop columns not needed ('publicAddress', 'caseNumber','offense', 'description', 'ucrCode') 
# These columns did not work in the model so droped them ('lat', 'lon','incidentDate', 'incidentTime' )

data_X = all_incidents_df.drop(['publicAddress', 'caseNumber','offense','description', 'ucrCode', 'lat', 'lon','incidentDate', 'incidentTime'], axis=1)
data_X.head()

  precinct neighborhood
0        5       Windom
1        5       Windom
2        3       Bryant
3        1  Loring Park
4        4      Folwell

In [23]:
# This made Precint and neighborhood into binary values for the model

data = data_X.copy()

data_binary_encoded = pd.get_dummies(data)
data_binary_encoded.head()

,precinct_1,precinct_1,precinct_18,precinct_2,precinct_2,precinct_3,precinct_3,precinct_4,precinct_4,precinct_5,...,neighborhood_Ventura Village,neighborhood_Victory,neighborhood_Waite Park,neighborhood_Webber - Camden,neighborhood_Wenonah,neighborhood_West Calhoun,neighborhood_Whittier,neighborhood_Willard - Hay,neighborhood_Windom,neighborhood_Windom Park
0,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
# This split the data into training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_binary_encoded, target_binary_encoded, random_state=42)
# y_train

In [25]:
#  This is the Random Forest model.  It has a very low fit score.
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.3935436761309605

# The code below was not used, but may be useful for other models

In [27]:
# This Code formats the date time for the columns.  Was not needed in the Random Forest Code

# all_incidents_df['incidentDate'] = pd.to_datetime(all_incidents_df['incidentDate'], format='%Y/%m/%d')
# all_incidents_df['incidentTime'] = pd.to_datetime(all_incidents_df['incidentTime'], format='%H:%M').dt.hour
# # all_incidents_df['incidentTime'] = parse(['incidentTime'].time())
# all_incidents_df.head()

In [12]:
# # scalaer needs to be on the training set

# from sklearn.preprocessing import StandardScaler
# X_scaler = StandardScaler().fit(X_train)
# y_scaler = StandardScaler().fit(y_train)

In [13]:
# scaler based on training is applied to the test data set

# X_train_scaled = X_scaler.transform(X_train)
# X_test_scaled = X_scaler.transform(X_test)
# y_train_scaled = y_scaler.transform(y_train)
# y_test_scaled = y_scaler.transform(y_test)

In [28]:
#Create random forest classifier. This model did not work since scaling descrete data does not really make sense 

# rf_model = RandomForestClassifier(n_estimators=200)
# rf_model.fit(X_train_scaled, y_train_scaled)
# # clf.score(X_test_scaled, y_test_scaled)